---
# tasks file for nagios-centos
- name: Install Dependencies
  yum:
    name:
      - compat-openssl10
      - perl
      - gcc
      - glibc
      - glibc-common
      - unzip
      - php
      - gd
      - gd-devel
      - postfix
    state: present

- name: Add Group in Nagios
  group:
    name: naggroup
    state: present

- name: Add User in Nagios
  user:
    name: naguser
    group: naggroup

- name: Install Nagios
  unarchive:
    src: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz
    dest: /tmp
    remote_src: YES

- name: Configure Nagios
  command: ./configure --with-command-group=naggroup
  args:
    chdir: /tmp/nagios-4.4.5

- name: make clean
  make:
    target: clean
    chdir: /tmp/nagios-4.4.5

- name: make all
  make:
    target: all
    chdir: /tmp/nagios-4.4.5

- name: make install-init
  make: 
    target: install-init
    chdir: /tmp/nagios-4.4.5

- name: make install-webconf
  make:
    target: install-webconf
    chdir: /tmp/nagios-4.4.5

- name: install passlib
  pip:
    name: passlib

- name: Create User in Nagios
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: user
    password: password

- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: YES

